
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 04 05:00:21 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int CHAR = 46;
  public static final int CONST = 8;
  public static final int MINUS_MINUS = 28;
  public static final int NOT_EQUAL = 30;
  public static final int CONTINUE = 43;
  public static final int LPAREN = 16;
  public static final int GREATER = 31;
  public static final int SEMI = 18;
  public static final int INTERFACE = 5;
  public static final int FOR = 40;
  public static final int LESS = 33;
  public static final int MINUS = 22;
  public static final int RPAREN = 17;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int BOOL = 47;
  public static final int COMMA = 19;
  public static final int CLASS = 4;
  public static final int PERC = 25;
  public static final int DIV = 24;
  public static final int LESS_EQUAL = 34;
  public static final int PLUS = 21;
  public static final int IF = 9;
  public static final int DOT = 20;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int PLUS_PLUS = 27;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 26;
  public static final int GREATER_EQUAL = 32;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 23;
  public static final int NUMBER = 44;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 39;
  public static final int LBRACE = 12;
  public static final int ELSE = 7;
  public static final int READ = 37;
  public static final int ENUM = 6;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 41;
  public static final int IMPLEMENTS = 42;
  public static final int EQUAL_EQUAL = 29;
  public static final int PRINT = 11;
}

